# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c138da52dac8e5eda30093387a322f08064567bf5d30121411fb0ecc9ab4881722183fe07c4c89cb108ebe0c10d08b75875b6bc858e27b857d4cb21860eddd7d

test:
  secret_key_base: 79bfc6cc2548f2cb2c3d520515ca7e374a1bdcaf8e25df1ef7b7bb593d7d09ce15f3422fff02530d111ec5337a45608bed7e942579a4516625ca46b617010bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
